label: Filer
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Gendan
          exposed_sorts_label: 'Sortér efter'
          sort_asc_label: Stigende
          sort_desc_label: Faldende
      pager:
        options:
          tags:
            previous: '‹ forrige'
            next: 'næste ›'
          expose:
            items_per_page_label: 'Antal elementer'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Forskydning
      fields:
        filename:
          label: Navn
        filesize:
          label: Størrelse
        status:
          label: Status
        count:
          label: 'Brugt i'
      filters:
        filename:
          expose:
            label: Filnavn
        status:
          expose:
            label: Status
      title: Filer
  page_1:
    display_options:
      menu:
        title: Filer
  page_2:
    display_title: 'File usage'
    display_options:
      pager:
        options:
          tags:
            previous: '‹ forrige'
            next: 'næste ›'
          expose:
            items_per_page_label: 'Antal elementer'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Forskydning
      fields:
        entity_label:
          label: Entitet
        type:
          label: Entitetstype
        count:
          label: 'Brug antal'
      title: 'File usage'
      arguments:
        fid:
          exception:
            title: Alle
