label: Indhold
description: 'Find og håndtér indhold.'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Gendan
          exposed_sorts_label: 'Sortér efter'
          sort_asc_label: Stigende
          sort_desc_label: Faldende
      pager:
        options:
          tags:
            previous: '‹ forrige'
            next: 'næste ›'
            first: '« første'
            last: 'sidste »'
      fields:
        title:
          label: Titel
        name:
          label: Forfatter
        status:
          label: Status
        changed:
          label: Opdateret
        operations:
          label: Handlinger
      filters:
        status:
          expose:
            label: Status
          group_info:
            label: Publiceringsstatus
            group_items:
              1:
                title: Udgivet
                value: '1'
        type:
          expose:
            label: Type
        title:
          expose:
            label: Titel
        langcode:
          expose:
            label: Sprog
      title: Indhold
      empty:
        area_text_custom:
          content: 'Der er intet indhold at vise.'
    display_title: Master
  page_1:
    display_options:
      menu:
        title: Indhold
      tab_options:
        title: Indhold
    display_title: Side
